FROM node:18

WORKDIR /app

# ✅ 소스 코드 복사
COPY .next .next
COPY public public
COPY src src
COPY package*.json ./
COPY next.config.js ./
COPY .env.production .env.production

ENV NODE_ENV=production

RUN npm ci --omit=dev

EXPOSE 3000

CMD ["npm", "run", "start"]
