version: "3.8"

services:
    nextjs:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nextjs
        restart: always
        volumes:
            - .:/app
            - /app/node_modules
        working_dir: /app
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
        command: "npm run start"

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf # 여기서 nginx.conf가 파일이어야 한다
            - ./nginx/conf.d:/etc/nginx/conf.d # conf.d 디렉토리도 올바르게 마운트
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/letsencrypt
        depends_on:
            - nextjs

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/letsencrypt
        entrypoint: >
            /bin/sh -c "trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew --webroot -w /var/www/certbot; done"
